### ISSUE TITLE
Gearman config tree fails with array of servers

### ISSUE THREAD

**Issue by gdbrown** [gdbots/pbjx-bundle-php#1]
```
console pbjx:gearman-consumer


  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "0" under "gdbots_pbjx.transport.gearman.servers"
```

with this config:

```
gdbots_pbjx:
  command_bus:
    transport: '%pbjx_command_bus_transport%'
  event_bus:
    transport: '%pbjx_event_bus_transport%'
  transport:
    gearman:
      servers:
        - {host: localhost, port: 4730}
```
